apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-token
  namespace: $NAMESPACE
  annotations:
    kubernetes.io/service-account.name: gitlab-deployer
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-deployer
  namespace: $NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: full-access
  namespace: $NAMESPACE
rules:
- apiGroups: [""]
  resources:
    ["namespaces", "serviceaccounts", "services", "secrets", "configmaps"]
  verbs: ["get", "list", "create", "update", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-deployer-full
  namespace: $NAMESPACE
subjects:
- kind: ServiceAccount
  name: gitlab-deployer
  namespace: $NAMESPACE
roleRef:
  kind: Role
  name: full-access
  apiGroup: rbac.authorization.k8s.io
