apiVersion: v1
kind: Namespace
metadata:
  name: solar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-manager
  namespace: solar
rules:
  - apiGroups: [""]
    resources:
      ["namespaces", "serviceaccounts", "services", "secrets", "configmaps"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: solar
subjects:
  - kind: ServiceAccount
    name: default
    namespace: git
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
