# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: prometheus-ingress
#   namespace: monitoring
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
#     traefik.ingress.kubernetes.io/router.middlewares: monitoring-ipwhitelist@kubernetescrd
#     cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
# spec:
#   ingressClassName: traefik
#   tls:
#     - hosts:
#         - prometheus.$DOMAIN
#       secretName: tls-prometheus
#   rules:
#     - host: prometheus.$DOMAIN
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: prometheus-stack-prometheus
#                 port:
#                   number: 9090
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: grafana-ingress
#   namespace: $NAMESPACE
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
#     traefik.ingress.kubernetes.io/router.middlewares: monitoring-ipwhitelist@kubernetescrd
#     cert-manager.io/cluster-issuer: "letsencrypt-cluster-issuer"
# spec:
#   ingressClassName: traefik
#   tls:
#     - hosts:
#         - grafana.$DOMAIN
#       secretName: tls-grafana
#   rules:
#     - host: grafana.$DOMAIN
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: prometheus-comunity-grafana
#                 port:
#                   number: 3000
# ---
