apiVersion: v1
kind: Namespace
metadata:
  name: tiktok
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-puller
  namespace: tiktok
imagePullSecrets:
  - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiktok-api
  namespace: tiktok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tiktok-api
  template:
    metadata:
      labels:
        app: tiktok-api
    spec:
      serviceAccountName: image-puller
      imagePullSecrets:
        - name: regcred
      containers:
        - name: tiktok-api
          imagePullPolicy: Always
          image: registry.booulder.xyz/repo_url
          envFrom:
            - secretRef:
                name: tiktok-api-secrets
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: tiktok-api
  namespace: tiktok
spec:
  type: ClusterIP
  selector:
    app: tiktok-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
